// convert-bootlogo.swift — BMP to embedded Swift boot logo converter
// Usage: swift Tools/convert-bootlogo.swift [input.bmp] [output.swift]
// Defaults: InkedFeather.bmp -> Sources/Application/UI/BootLogo.swift

import Foundation

// MARK: - Configuration

let nativeWidth = 800
let nativeHeight = 480
let bytesPerNativeRow = nativeWidth / 8  // 100
let bufferSize = nativeWidth * nativeHeight / 8  // 48000

let chunkCount = 8
let rowsPerChunk = nativeHeight / chunkCount  // 60
let bytesPerChunk = rowsPerChunk * bytesPerNativeRow  // 6000
let uint64PerChunk = bytesPerChunk / 8  // 750

// MARK: - BMP Parsing

let args = CommandLine.arguments
let inputPath = args.count > 1 ? args[1] : "InkedFeather.bmp"
let outputPath = args.count > 2 ? args[2] : "Sources/Application/UI/BootLogo.swift"

guard let bmpData = try? Data(contentsOf: URL(fileURLWithPath: inputPath)) else {
    fputs("Error: cannot read \(inputPath)\n", stderr)
    exit(1)
}

func readU16(_ data: Data, _ offset: Int) -> UInt16 {
    UInt16(data[offset]) | UInt16(data[offset + 1]) << 8
}
func readU32(_ data: Data, _ offset: Int) -> UInt32 {
    UInt32(data[offset]) | UInt32(data[offset + 1]) << 8 |
    UInt32(data[offset + 2]) << 16 | UInt32(data[offset + 3]) << 24
}
func readI32(_ data: Data, _ offset: Int) -> Int32 {
    Int32(bitPattern: readU32(data, offset))
}

// Validate BMP header
guard bmpData.count >= 62,
      bmpData[0] == 0x42, bmpData[1] == 0x4D else {  // "BM"
    fputs("Error: not a valid BMP file\n", stderr)
    exit(1)
}

let dataOffset = Int(readU32(bmpData, 10))
let bmpWidth = Int(readI32(bmpData, 18))
let bmpHeight = Int(readI32(bmpData, 22))
let bpp = Int(readU16(bmpData, 28))
let compression = readU32(bmpData, 30)

guard bmpWidth == 480, abs(bmpHeight) == 800, bpp == 1, compression == 0 else {
    fputs("Error: expected 480x800 1-bit uncompressed BMP, got \(bmpWidth)x\(abs(bmpHeight)) \(bpp)bpp comp=\(compression)\n", stderr)
    exit(1)
}

let bottomUp = bmpHeight > 0
let bmpRowStride = ((bmpWidth + 31) / 32) * 4  // 60

// Validate palette: palette[0] should be black
let dibHeaderSize = Int(readU32(bmpData, 14))
let paletteOffset = 14 + dibHeaderSize
let p0r = bmpData[paletteOffset + 2]
let p0g = bmpData[paletteOffset + 1]
let p0b = bmpData[paletteOffset + 0]
if p0r != 0 || p0g != 0 || p0b != 0 {
    fputs("Warning: palette[0] is not black (R=\(p0r) G=\(p0g) B=\(p0b)), colors may be inverted\n", stderr)
}

fputs("Input: \(bmpWidth)x\(abs(bmpHeight)) 1-bit BMP, \(bottomUp ? "bottom-up" : "top-down")\n", stderr)

// MARK: - Rotation: Logical 480x800 → Native 800x480

// Allocate native buffer
var nativeBuffer = [UInt8](repeating: 0xFF, count: bufferSize)

// For each native pixel (nx, ny):
//   logical x = 479 - ny
//   logical y = nx
//   BMP row = bottomUp ? (799 - logical_y) : logical_y = bottomUp ? (799 - nx) : nx
//   BMP col = logical_x = 479 - ny

for ny in 0..<nativeHeight {
    let lx = 479 - ny
    let bmpCol = lx

    for nxByte in 0..<bytesPerNativeRow {
        var outByte: UInt8 = 0
        for bit in 0..<8 {
            let nx = nxByte * 8 + bit
            let ly = nx
            let bmpRow = bottomUp ? (799 - ly) : ly

            let srcByteIndex = dataOffset + bmpRow * bmpRowStride + bmpCol / 8
            let srcBitIndex = 7 - (bmpCol & 7)
            let pixel = (bmpData[srcByteIndex] >> srcBitIndex) & 1

            // pixel: 0=black, 1=white (matches framebuffer convention)
            outByte |= pixel << (7 - bit)
        }
        nativeBuffer[ny * bytesPerNativeRow + nxByte] = outByte
    }
}

fputs("Rotated to native \(nativeWidth)x\(nativeHeight) layout (\(bufferSize) bytes)\n", stderr)

// MARK: - Generate Swift Source

var output = """
// Auto-generated by Tools/convert-bootlogo.swift — do not edit.
// Source: \(inputPath) (480x800 1-bit BMP)
// Native layout: \(nativeWidth)x\(nativeHeight), pre-rotated, LE pre-swapped.

/// \(bytesPerChunk) bytes stored as \(uint64PerChunk) x UInt64.
/// Pre-swapped for little-endian: raw memory matches native framebuffer byte order.
struct StaticArray\(bytesPerChunk) {
    let storage: (\n
"""

// Generate tuple type declaration (750 UInt64 elements)
for i in 0..<uint64PerChunk {
    let isLast = i == uint64PerChunk - 1
    let lineStart = i % 8 == 0
    let lineEnd = i % 8 == 7 || isLast

    if lineStart {
        output += "        "
    }
    output += "UInt64"
    if !isLast {
        output += ", "
    }
    if lineEnd {
        output += " // \(i / 8 * 8)-\(i)\n"
    }
}

output += """
    )

    /// Access byte at index (no endian correction needed — data is pre-swapped for LE).
    func byte(at index: Int) -> UInt8 {
        withUnsafePointer(to: storage) { ptr in
            UnsafeRawPointer(ptr).load(fromByteOffset: index, as: UInt8.self)
        }
    }
}

/// Boot logo pixel data: \(nativeWidth)x\(nativeHeight) native layout, split into \(chunkCount) chunks of \(rowsPerChunk) rows each.
enum BootLogoData {
"""

for c in 0..<chunkCount {
    output += "    static let chunk\(c): StaticArray\(bytesPerChunk) = makeChunk\(c)()\n"
}

output += "}\n\n"

// Generate makeChunkN() functions
for c in 0..<chunkCount {
    let chunkOffset = c * bytesPerChunk
    output += "private func makeChunk\(c)() -> StaticArray\(bytesPerChunk) {\n"
    output += "    StaticArray\(bytesPerChunk)(storage: (\n"

    for i in 0..<uint64PerChunk {
        let byteOffset = chunkOffset + i * 8

        // LE pre-swap: bytes [b0,b1,b2,b3,b4,b5,b6,b7] → 0xb7b6b5b4_b3b2b1b0
        // On RISC-V LE, UInt64 stores LSB first, so memory layout will be b0,b1,...,b7
        var val: UInt64 = 0
        for j in 0..<8 {
            val |= UInt64(nativeBuffer[byteOffset + j]) << (j * 8)
        }

        let isLast = i == uint64PerChunk - 1
        let lineStart = i % 4 == 0
        let lineEnd = i % 4 == 3 || isLast

        if lineStart {
            output += "        "
        }
        output += String(format: "0x%016llX", val)
        if !isLast {
            output += ", "
        }
        if lineEnd {
            output += "\n"
        }
    }

    output += "    ))\n}\n\n"
}

// Generate BootLogo enum
output += """
/// Boot logo renderer.
enum BootLogo {
    static func draw(fb: Framebuffer) {

"""

for c in 0..<chunkCount {
    output += "        copyChunk(BootLogoData.chunk\(c), to: fb, offset: \(c * bytesPerChunk))\n"
}

output += """
    }

    private static func copyChunk(_ chunk: StaticArray\(bytesPerChunk), to fb: Framebuffer, offset: Int) {
        withUnsafePointer(to: chunk.storage) { ptr in
            fb.copyToNativeBuffer(
                from: UnsafeRawPointer(ptr).assumingMemoryBound(to: UInt8.self),
                offset: offset, count: \(bytesPerChunk))
        }
    }
}
"""

// Write output
do {
    try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
    fputs("Generated \(outputPath) (\(output.count) bytes)\n", stderr)
} catch {
    fputs("Error writing \(outputPath): \(error)\n", stderr)
    exit(1)
}
